### ISSUE TITLE
Use Twine instead of `poetry publish`

### ISSUE THREAD

**Issue by apatel762** [apatel762/pretty-history#26]
https://twine.readthedocs.io/en/latest/

So, the flow would look something like this:

1. Install Poetry
2. `poetry build`
3. Install Twine
4. `twine upload dist/*`

...and in the step where we upload to PyPi, we need to inject the API key slightly differently:

```yaml
jobs:
  publish:
    steps:
      - name: Publish the project to PyPi
        env:
          TWINE_REPOSITORY: pypi
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: |
          twine upload dist/*
```
